Pdssj-473 update gradle
caplin/project-templates pull request #21
Opened 2022-03-28 15:21 UTC by jiaxuanA

2022-03-30 08:01 UTC, Faris-Mckay requested changes

2022-03-30 08:01 UTC, Faris-Mckay commented on permissioning-template/build.gradle
> -    //compile fileTree(dir: 'lib', include: '*.jar')
This change needs to be reverted

2022-03-30 08:01 UTC, Faris-Mckay commented on permissioning-template/build.gradle
> -    compile(group: 'com.caplin.platform.integration.java', name: 'datasource', version: '7.0.+')
Why have we commented this ? Should be uncommmented

2022-03-30 08:01 UTC, Faris-Mckay commented on permissioning-template/build.gradle
> -    compile(group: 'com.caplin.platform.integration.java', name: 'permissioning-datasource', version: '7.0.+')
+ Same as above

2022-03-30 08:01 UTC, Faris-Mckay commented on permissioning-template/build.gradle
> -    mavenCentral()
All of this stuff should be uncommented, it should be the default way for customers to connect externally

2022-03-30 08:01 UTC, Faris-Mckay commented on jtm-legacy-template/gradle/wrapper/gradle-wrapper.properties
> +#Thu Nov 24 12:19:17 GMT 2016
I don't think we need to add a new wrapper for this project, but its a minor change doesn't matter either way.

2022-03-30 08:01 UTC, Faris-Mckay commented on pricing-template-dotnet/build.gradle
> -apply plugin: "maven"
Make sure to check the documentation for this change because this means "uploadArchives" command now becomes "publish" instead, so we need to update any README references for that.

2022-03-30 08:01 UTC, Faris-Mckay commented on pricing-template-dotnet/build.gradle
> +        allowInsecureProtocol = true
What is this for? I don't think we should have this by default

2022-03-30 08:01 UTC, Faris-Mckay commented on trading-template/build.gradle
> -    mavenCentral()
Same as above, this whole block should not be commented

2022-03-30 08:01 UTC, Faris-Mckay commented on trading-template/build.gradle
> -    //compile fileTree(dir: 'lib', include: '*.jar')
Same as above

2022-03-30 08:01 UTC, Faris-Mckay commented on trading-template/build.gradle
> -    compile(group: 'com.caplin.platform.integration.java', name: 'datasource', version: '7.0.+')
Same as above

2022-03-30 08:01 UTC, Faris-Mckay commented on trading-template/build.gradle
> -    compile(group: 'com.caplin.platform.integration.java', name: 'trading-datasource', version: '7.0.+')
Same as above

2022-03-31 08:38 UTC, jiaxuanA commented on jtm-legacy-template/gradle/wrapper/gradle-wrapper.properties
> +#Thu Nov 24 12:19:17 GMT 2016
This project dont have a wrapper before.

2022-03-31 08:39 UTC, jiaxuanA commented on pricing-template-dotnet/build.gradle
> +        allowInsecureProtocol = true
this one is for the problem for the new gradle version. It will think http as unsecure and dont get the dependencies.

2022-03-31 08:40 UTC, jiaxuanA commented on pricing-template-dotnet/build.gradle
> +        allowInsecureProtocol = true
you can se details from this link, the first answer https://stackoverflow.com/questions/68585885/allow-insecure-protocols-android-gradle

2022-03-31 08:48 UTC, jiaxuanA commented on permissioning-template/build.gradle
> -    //compile fileTree(dir: 'lib', include: '*.jar')
change it back

2022-03-31 08:48 UTC, jiaxuanA commented on permissioning-template/build.gradle
> -    compile(group: 'com.caplin.platform.integration.java', name: 'datasource', version: '7.0.+')
change is back now

2022-03-31 08:48 UTC, jiaxuanA commented on permissioning-template/build.gradle
> -    compile(group: 'com.caplin.platform.integration.java', name: 'permissioning-datasource', version: '7.0.+')
change is back now

2022-03-31 08:48 UTC, jiaxuanA commented on permissioning-template/build.gradle
> -    mavenCentral()
change is back now

2022-03-31 08:50 UTC, jiaxuanA commented on pricing-template-dotnet/build.gradle
> -apply plugin: "maven"
checked, we dont have any uploadArchives related in Readme

2022-03-31 08:55 UTC, jiaxuanA commented on trading-template/build.gradle
> -    mavenCentral()
done

2022-03-31 08:56 UTC, jiaxuanA commented on trading-template/build.gradle
> -    //compile fileTree(dir: 'lib', include: '*.jar')
done

2022-03-31 08:56 UTC, jiaxuanA commented on trading-template/build.gradle
> -    compile(group: 'com.caplin.platform.integration.java', name: 'trading-datasource', version: '7.0.+')
done

2022-05-27 10:44 UTC, merged